version: '3'
services:
  postgres:
    image: postgres:15
    container_name: spawn-db
    networks:
      - spawn
    ports:
      - '7654:5432'
    restart: always
    environment:
      POSTGRES_USER: spawn
      POSTGRES_PASSWORD: spawn
    command: ['postgres', '-c', 'log_statement=all']

networks:
  spawn:
    name: spawn
